version: "3"
services:
  elasticsearch:
    image: elasticsearch:6.5.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - default
      - elk
  kibana:
    image: kibana:6.5.3
    container_name: kibana
    ports:
      - "5601:5601"
    links:
      - elasticsearch:elasticsearch
    networks:
      - default
      - elk
    environment:
      SERVER_NAME: localhost
      SERVER_PORT: 5601
      ELASTICSEARCH_HOSTS: http://172.20.0.2:9200
networks:
  elk:
    external: true